//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form method=&quot;post&quot; action=&quot;a2b.php&quot;&gt;
        ///	
        ///	&lt;table id=&quot;short_info&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot;&gt;
        ///		&lt;tbody&gt;&lt;tr&gt;
        ///			&lt;th&gt;Destination:&lt;/th&gt;
        ///			&lt;td&gt;&lt;a href=&quot;karte.php?d=538519&amp;amp;c=31&quot;&gt;loazy Village (-154|-272)&lt;/a&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Player:&lt;/th&gt;
        ///			&lt;td&gt;&lt;a href=&quot;spieler.php?uid=96983&quot;&gt;loazy&lt;/a&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;&lt;/tbody&gt;
        ///	&lt;/table&gt;
        ///		
        ///	&lt;table class=&quot;troop_details&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot;&gt;
        ///		&lt;thead&gt;
        ///			&lt;tr&gt;
        ///				&lt;td&gt;sz&lt;/td&gt;
        ///				&lt;td colspan=&quot;10&quot;&gt;Raiding loazy Village&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///		&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmForm {
            get {
                return ResourceManager.GetString("ConfirmForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///			&lt;td class=&quot;role&quot;&gt;&lt;a href=&quot;karte.php?d=540121&amp;c=5c&quot;&gt;sz&lt;/a&gt;&lt;/td&gt;&lt;td colspan=&quot;10&quot;&gt;&lt;a href=&quot;karte.php?d=540119&amp;c=1d&quot;&gt;Raid on Sharledla Village&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody class=&quot;units&quot;&gt;&lt;tr&gt;&lt;th&gt;&amp;nbsp;&lt;/th&gt;&lt;td&gt;&lt;img src=&quot;img/x.gif&quot; class=&quot;unit u11&quot; title=&quot;Maceman&quot; alt=&quot;Maceman&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;img src=&quot;img/x.gif&quot; class=&quot;unit u12&quot; title=&quot;Spearman&quot; alt=&quot;Spearman&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;img src=&quot;img/x.gif&quot; class=&quot;unit u13&quot; title=&quot;Axeman&quot; alt=&quot;Axeman&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;img src=&quot;img/x.gif&quot; class=&quot;unit u14&quot; title=&quot;Scout&quot; alt=&quot;Scout [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmResult {
            get {
                return ResourceManager.GetString("ConfirmResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body class=&quot;v35 ie ie8&quot;&gt;
        ///&lt;h1&gt;Rally Point &lt;span class=&quot;level&quot;&gt;level 3&lt;/span&gt;&lt;/h1&gt;
        ///&lt;p class=&quot;build_desc&quot;&gt;The village&apos;s troops meet at the rally point. From here you can send them out to reinforce, raid, or conquer another village.&lt;/p&gt;
        /// 
        ///&lt;div id=&quot;textmenu&quot;&gt;
        ///		&lt;a href=&quot;build.php?id=39&quot;&gt;Overview&lt;/a&gt; |
        ///		&lt;a href=&quot;a2b.php&quot;&gt;Send troops&lt;/a&gt; |
        ///		&lt;a href=&quot;warsim.php&quot;&gt;Combat Simulator&lt;/a&gt;&lt;/div&gt;&lt;h4&gt;
        ///						Incoming troops (7)&lt;/h4&gt;&lt;table class=&quot;troop_details&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot;&gt;
        ///	&lt;thead&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RallyPointCrazy {
            get {
                return ResourceManager.GetString("RallyPointCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body class=&quot;v35 gecko gecko3_5_x&quot;&gt;
        ///&lt;h1&gt;Rally Point &lt;span class=&quot;level&quot;&gt;level 1&lt;/span&gt;&lt;/h1&gt;
        ///&lt;p class=&quot;build_desc&quot;&gt;The village&apos;s troops meet at the rally point. From here you can send them out to reinforce, raid, or conquer another village.&lt;/p&gt;
        ///
        ///&lt;div id=&quot;textmenu&quot;&gt;
        ///		&lt;a href=&quot;build.php?id=39&quot;&gt;Overview&lt;/a&gt; |
        ///		&lt;a href=&quot;a2b.php&quot;&gt;Send troops&lt;/a&gt; |
        ///		&lt;a href=&quot;warsim.php&quot;&gt;Combat Simulator&lt;/a&gt;&lt;/div&gt;&lt;h4&gt;Troops in the village&lt;/h4&gt;&lt;table class=&quot;troop_details&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot;&gt;
        ///	&lt;thead&gt;
        ///		&lt;tr&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RallyPointTiny {
            get {
                return ResourceManager.GetString("RallyPointTiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Send troops&lt;/h1&gt;
        ///&lt;form method=&quot;POST&quot; name=&quot;snd&quot; action=&quot;a2b.php&quot;&gt;
        ///	&lt;input type=&quot;hidden&quot; name=&quot;timestamp&quot; value=&quot;1259379679&quot; /&gt;
        ///	&lt;input type=&quot;hidden&quot; name=&quot;timestamp_checksum&quot; value=&quot;719106&quot; /&gt;
        ///	&lt;input type=&quot;hidden&quot; name=&quot;b&quot; value=&quot;1&quot; /&gt;
        /// 
        /// 
        ///		&lt;table id=&quot;troops&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td class=&quot;line-first column-first&quot;&gt;
        ///				&lt;img class=&quot;unit u11&quot; src=&quot;img/x.gif&quot; title=&quot;Maceman&quot; onclick=&quot;document.snd.t1.value=&apos;&apos;; return false;&quot; alt=&quot;Maceman&quot; /&gt;
        ///				&lt;input type=&quot;text&quot; class=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendTroopsForm {
            get {
                return ResourceManager.GetString("SendTroopsForm", resourceCulture);
            }
        }
    }
}
