//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeifenLuo.WinFormsUI.Docking

import System



// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '2.0.0.0')]
[System.Diagnostics.DebuggerNonUserCodeAttribute]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute]
internal class Resources:

	
	private static resourceMan as System.Resources.ResourceManager

	
	private static resourceCulture as System.Globalization.CultureInfo

	
	[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
	internal def constructor():
		pass

	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	internal static ResourceManager as System.Resources.ResourceManager:
		get:
			if object.ReferenceEquals(resourceMan, null):
				temp as System.Resources.ResourceManager = System.Resources.ResourceManager('WeifenLuo.WinFormsUI.Docking.Resources', typeof(Resources).Assembly)
				resourceMan = temp
			return resourceMan

	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	internal static Culture as System.Globalization.CultureInfo:
		get:
			return resourceCulture
		set:
			resourceCulture = value

	
	internal static DockIndicator_PaneDiamond as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_Bottom as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_Bottom', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_Fill as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_Fill', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_HotSpot as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_HotSpot', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_HotSpotIndex as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_HotSpotIndex', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_Left as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_Left', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_Right as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_Right', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PaneDiamond_Top as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PaneDiamond_Top', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelBottom as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelBottom', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelBottom_Active as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelBottom_Active', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelFill as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelFill', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelFill_Active as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelFill_Active', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelLeft as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelLeft', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelLeft_Active as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelLeft_Active', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelRight as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelRight', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelRight_Active as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelRight_Active', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelTop as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelTop', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockIndicator_PanelTop_Active as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockIndicator_PanelTop_Active', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockPane_AutoHide as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockPane_AutoHide', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockPane_Close as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockPane_Close', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockPane_Dock as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockPane_Dock', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockPane_Option as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockPane_Option', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

	
	internal static DockPane_OptionOverflow as System.Drawing.Bitmap:
		get:
			obj as object = ResourceManager.GetObject('DockPane_OptionOverflow', resourceCulture)
			return cast(System.Drawing.Bitmap, obj)

