//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeifenLuo.WinFormsUI.Docking

import System



// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '2.0.0.0')]
[System.Diagnostics.DebuggerNonUserCodeAttribute]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute]
internal class Strings:

	
	private static resourceMan as System.Resources.ResourceManager

	
	private static resourceCulture as System.Globalization.CultureInfo

	
	[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
	internal def constructor():
		pass

	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	internal static ResourceManager as System.Resources.ResourceManager:
		get:
			if object.ReferenceEquals(resourceMan, null):
				temp as System.Resources.ResourceManager = System.Resources.ResourceManager('WeifenLuo.WinFormsUI.Docking.Strings', typeof(Strings).Assembly)
				resourceMan = temp
			return resourceMan

	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	internal static Culture as System.Globalization.CultureInfo:
		get:
			return resourceCulture
		set:
			resourceCulture = value

	
	internal static Category_Docking as string:
		get:
			return ResourceManager.GetString('Category_Docking', resourceCulture)

	
	internal static Category_DockingNotification as string:
		get:
			return ResourceManager.GetString('Category_DockingNotification', resourceCulture)

	
	internal static Category_PropertyChanged as string:
		get:
			return ResourceManager.GetString('Category_PropertyChanged', resourceCulture)

	
	internal static DockAreaEditor_FloatCheckBoxText as string:
		get:
			return ResourceManager.GetString('DockAreaEditor_FloatCheckBoxText', resourceCulture)

	
	internal static DockContent_AllowEndUserDocking_Description as string:
		get:
			return ResourceManager.GetString('DockContent_AllowEndUserDocking_Description', resourceCulture)

	
	internal static DockContent_AutoHidePortion_Description as string:
		get:
			return ResourceManager.GetString('DockContent_AutoHidePortion_Description', resourceCulture)

	
	internal static DockContent_CloseButton_Description as string:
		get:
			return ResourceManager.GetString('DockContent_CloseButton_Description', resourceCulture)

	
	internal static DockContent_Constructor_InvalidForm as string:
		get:
			return ResourceManager.GetString('DockContent_Constructor_InvalidForm', resourceCulture)

	
	internal static DockContent_DockAreas_Description as string:
		get:
			return ResourceManager.GetString('DockContent_DockAreas_Description', resourceCulture)

	
	internal static DockContent_DockStateChanged_Description as string:
		get:
			return ResourceManager.GetString('DockContent_DockStateChanged_Description', resourceCulture)

	
	internal static DockContent_HideOnClose_Description as string:
		get:
			return ResourceManager.GetString('DockContent_HideOnClose_Description', resourceCulture)

	
	internal static DockContent_ShowHint_Description as string:
		get:
			return ResourceManager.GetString('DockContent_ShowHint_Description', resourceCulture)

	
	internal static DockContent_TabPageContextMenu_Description as string:
		get:
			return ResourceManager.GetString('DockContent_TabPageContextMenu_Description', resourceCulture)

	
	internal static DockContent_TabText_Description as string:
		get:
			return ResourceManager.GetString('DockContent_TabText_Description', resourceCulture)

	
	internal static DockContent_ToolTipText_Description as string:
		get:
			return ResourceManager.GetString('DockContent_ToolTipText_Description', resourceCulture)

	
	internal static DockContentHandler_AutoHidePortion_OutOfRange as string:
		get:
			return ResourceManager.GetString('DockContentHandler_AutoHidePortion_OutOfRange', resourceCulture)

	
	internal static DockContentHandler_DockAreas_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockContentHandler_DockAreas_InvalidValue', resourceCulture)

	
	internal static DockContentHandler_DockPane_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockContentHandler_DockPane_InvalidValue', resourceCulture)

	
	internal static DockContentHandler_FloatPane_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockContentHandler_FloatPane_InvalidValue', resourceCulture)

	
	internal static DockContentHandler_IsFloat_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockContentHandler_IsFloat_InvalidValue', resourceCulture)

	
	internal static DockContentHandler_SetDockState_InvalidState as string:
		get:
			return ResourceManager.GetString('DockContentHandler_SetDockState_InvalidState', resourceCulture)

	
	internal static DockContentHandler_SetDockState_NullPanel as string:
		get:
			return ResourceManager.GetString('DockContentHandler_SetDockState_NullPanel', resourceCulture)

	
	internal static DockContentHandler_Show_InvalidBeforeContent as string:
		get:
			return ResourceManager.GetString('DockContentHandler_Show_InvalidBeforeContent', resourceCulture)

	
	internal static DockContentHandler_Show_InvalidDockState as string:
		get:
			return ResourceManager.GetString('DockContentHandler_Show_InvalidDockState', resourceCulture)

	
	internal static DockContentHandler_Show_InvalidPrevPane as string:
		get:
			return ResourceManager.GetString('DockContentHandler_Show_InvalidPrevPane', resourceCulture)

	
	internal static DockContentHandler_Show_NullDockPanel as string:
		get:
			return ResourceManager.GetString('DockContentHandler_Show_NullDockPanel', resourceCulture)

	
	internal static DockContentHandler_Show_NullPane as string:
		get:
			return ResourceManager.GetString('DockContentHandler_Show_NullPane', resourceCulture)

	
	internal static DockContentHandler_ShowHint_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockContentHandler_ShowHint_InvalidValue', resourceCulture)

	
	internal static DockHandler_TabPageContextMenuStrip_Description as string:
		get:
			return ResourceManager.GetString('DockHandler_TabPageContextMenuStrip_Description', resourceCulture)

	
	internal static DockIndicator_ToolTipText as string:
		get:
			return ResourceManager.GetString('DockIndicator_ToolTipText', resourceCulture)

	
	internal static DockPane_ActiveContent_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockPane_ActiveContent_InvalidValue', resourceCulture)

	
	internal static DockPane_Constructor_NullContent as string:
		get:
			return ResourceManager.GetString('DockPane_Constructor_NullContent', resourceCulture)

	
	internal static DockPane_Constructor_NullDockPanel as string:
		get:
			return ResourceManager.GetString('DockPane_Constructor_NullDockPanel', resourceCulture)

	
	internal static DockPane_DockTo_InvalidContainer as string:
		get:
			return ResourceManager.GetString('DockPane_DockTo_InvalidContainer', resourceCulture)

	
	internal static DockPane_DockTo_NoPrevPane as string:
		get:
			return ResourceManager.GetString('DockPane_DockTo_NoPrevPane', resourceCulture)

	
	internal static DockPane_DockTo_NullContainer as string:
		get:
			return ResourceManager.GetString('DockPane_DockTo_NullContainer', resourceCulture)

	
	internal static DockPane_DockTo_NullPrevPane as string:
		get:
			return ResourceManager.GetString('DockPane_DockTo_NullPrevPane', resourceCulture)

	
	internal static DockPane_DockTo_SelfPrevPane as string:
		get:
			return ResourceManager.GetString('DockPane_DockTo_SelfPrevPane', resourceCulture)

	
	internal static DockPane_FloatWindow_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockPane_FloatWindow_InvalidValue', resourceCulture)

	
	internal static DockPane_SetContentIndex_InvalidContent as string:
		get:
			return ResourceManager.GetString('DockPane_SetContentIndex_InvalidContent', resourceCulture)

	
	internal static DockPane_SetContentIndex_InvalidIndex as string:
		get:
			return ResourceManager.GetString('DockPane_SetContentIndex_InvalidIndex', resourceCulture)

	
	internal static DockPane_SetDockState_InvalidState as string:
		get:
			return ResourceManager.GetString('DockPane_SetDockState_InvalidState', resourceCulture)

	
	internal static DockPaneCaption_ToolTipAutoHide as string:
		get:
			return ResourceManager.GetString('DockPaneCaption_ToolTipAutoHide', resourceCulture)

	
	internal static DockPaneCaption_ToolTipClose as string:
		get:
			return ResourceManager.GetString('DockPaneCaption_ToolTipClose', resourceCulture)

	
	internal static DockPaneCaption_ToolTipOptions as string:
		get:
			return ResourceManager.GetString('DockPaneCaption_ToolTipOptions', resourceCulture)

	
	internal static DockPanel_ActiveAutoHideContent_InvalidValue as string:
		get:
			return ResourceManager.GetString('DockPanel_ActiveAutoHideContent_InvalidValue', resourceCulture)

	
	internal static DockPanel_ActiveContentChanged_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_ActiveContentChanged_Description', resourceCulture)

	
	internal static DockPanel_ActiveDocumentChanged_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_ActiveDocumentChanged_Description', resourceCulture)

	
	internal static DockPanel_ActivePaneChanged_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_ActivePaneChanged_Description', resourceCulture)

	
	internal static DockPanel_AllowEndUserDocking_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_AllowEndUserDocking_Description', resourceCulture)

	
	internal static DockPanel_AllowEndUserNestedDocking_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_AllowEndUserNestedDocking_Description', resourceCulture)

	
	internal static DockPanel_ContentAdded_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_ContentAdded_Description', resourceCulture)

	
	internal static DockPanel_ContentRemoved_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_ContentRemoved_Description', resourceCulture)

	
	internal static DockPanel_DefaultFloatWindowSize_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_DefaultFloatWindowSize_Description', resourceCulture)

	
	internal static DockPanel_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_Description', resourceCulture)

	
	internal static DockPanel_DockBottomPortion_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_DockBottomPortion_Description', resourceCulture)

	
	internal static DockPanel_DockLeftPortion_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_DockLeftPortion_Description', resourceCulture)

	
	internal static DockPanel_DockRightPortion_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_DockRightPortion_Description', resourceCulture)

	
	internal static DockPanel_DockTopPortion_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_DockTopPortion_Description', resourceCulture)

	
	internal static DockPanel_DocumentStyle_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_DocumentStyle_Description', resourceCulture)

	
	internal static DockPanel_LoadFromXml_AlreadyInitialized as string:
		get:
			return ResourceManager.GetString('DockPanel_LoadFromXml_AlreadyInitialized', resourceCulture)

	
	internal static DockPanel_LoadFromXml_InvalidFormatVersion as string:
		get:
			return ResourceManager.GetString('DockPanel_LoadFromXml_InvalidFormatVersion', resourceCulture)

	
	internal static DockPanel_LoadFromXml_InvalidXmlFormat as string:
		get:
			return ResourceManager.GetString('DockPanel_LoadFromXml_InvalidXmlFormat', resourceCulture)

	
	internal static DockPanel_ParentForm_Invalid as string:
		get:
			return ResourceManager.GetString('DockPanel_ParentForm_Invalid', resourceCulture)

	
	internal static DockPanel_Persistor_XmlFileComment1 as string:
		get:
			return ResourceManager.GetString('DockPanel_Persistor_XmlFileComment1', resourceCulture)

	
	internal static DockPanel_Persistor_XmlFileComment2 as string:
		get:
			return ResourceManager.GetString('DockPanel_Persistor_XmlFileComment2', resourceCulture)

	
	internal static DockPanel_RightToLeftLayout_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_RightToLeftLayout_Description', resourceCulture)

	
	internal static DockPanel_SetPaneIndex_InvalidIndex as string:
		get:
			return ResourceManager.GetString('DockPanel_SetPaneIndex_InvalidIndex', resourceCulture)

	
	internal static DockPanel_SetPaneIndex_InvalidPane as string:
		get:
			return ResourceManager.GetString('DockPanel_SetPaneIndex_InvalidPane', resourceCulture)

	
	internal static DockPanel_ShowDocumentIcon_Description as string:
		get:
			return ResourceManager.GetString('DockPanel_ShowDocumentIcon_Description', resourceCulture)

	
	internal static DockPaneStrip_ToolTipClose as string:
		get:
			return ResourceManager.GetString('DockPaneStrip_ToolTipClose', resourceCulture)

	
	internal static DockPaneStrip_ToolTipWindowList as string:
		get:
			return ResourceManager.GetString('DockPaneStrip_ToolTipWindowList', resourceCulture)

	
	internal static FloatWindow_Constructor_NullDockPanel as string:
		get:
			return ResourceManager.GetString('FloatWindow_Constructor_NullDockPanel', resourceCulture)

	
	internal static FloatWindow_SetPaneIndex_InvalidIndex as string:
		get:
			return ResourceManager.GetString('FloatWindow_SetPaneIndex_InvalidIndex', resourceCulture)

	
	internal static FloatWindow_SetPaneIndex_InvalidPane as string:
		get:
			return ResourceManager.GetString('FloatWindow_SetPaneIndex_InvalidPane', resourceCulture)

	
	internal static IDockDragSource_DockTo_InvalidPanel as string:
		get:
			return ResourceManager.GetString('IDockDragSource_DockTo_InvalidPanel', resourceCulture)

